---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulletin-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBaWAZ24hh0wqeMsckzXvywcMEr59NVG7Bh5OMr1roERLBkGJbkL2mhCL5xUlgNoDV4B/Vxlb16BsxgY22/Mrd2GTRNu2b16ylTA6bWFprp2V/Pu/RKiGDM3isdDhxPOifcFFwkspH33M3/p+wEQDDohBYBrN4tMIj6NkHz4WP1bSgzzVjmX6Q1Qaglrguz0k3RD9Cc/shcrLXjC8mvSMXXFYC2Y1aqQSp7fBUDdAR6TMEP6tCLvA2FErCE8EGUb+seLZPNgehLTB61uHM2tflyvxKb5v8UN9XXjJExGlf3jGowpiDReKitg4anjww24yvq+NG395e/PGbPdIrCWNs4kJhcgAfrNTXUuSWNScSw81LapVrVhpsMpZRdHMJ3/RrMLxEeKdAJudTyhTDQZiOINson3kV1f+WLeW+GBzVt8XQQ+Ivg7yEl9+fPS1N4zmFZJL7ZxN4FB3fnewCT6hDSt4wGlT+bHzOQWwdgDQqadRLT+JRRkPvHINAJZFZDz1PTlBRXzJbT6yoreCdCsS5gOroeVSvvS9ExW155KRIEOgVYkua3zSQe82DKA6ex/g+VUK441r8BqcvmxsB35loiLSkSMieslMtTLzTQR4Vf702z2v0BF8TwzsEd5VlAN4N7wNTe6NSP0M2LpJNn8SFjjSxlzbUmbTSH2SfdyKf+vMFBrSxOsaGUSU9d3a2KtF4RZDwmGICkVToXw0Ohqz/ACVAGOm7fVS00N/Lz5FC9PIMjQp8nz3CBROVKcCe2Y+n+k5W8mbWe+VG9Brbuxe2LqgOTJkDylg+wwRrFOBYemg52oIJeVfw7CpBRq49kf6UZEZriLCU9TqugXjp4PeAu8WXNZaZCbcUU0Cq7PBZheYgV++lVTjgXjNHNOGtqyiHrNHV9tfJWAjfOIvTznbeYibsS7gpTQnfQ9iuq4boO
  template:
    metadata:
      name: bulletin-tunnel-credentials
      namespace: cloudflare
    type: Opaque
