---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bulletin-tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBj5iEWLlxRSoGPVNAoojziNvVIgGrHLlHR6TqMkAvW3CUiT+Y/ObTzhsq5r4uBB83/u/8lmZ4oBOXu9G4YxmMkfrxfgF2jBUk4F4eR4nxrt5SFS/0SzF/lAbhNPR6wXyXl+UIF8tbVMoieJ0fMjSHwtHzHr6E/lejjrSUUQfkjHUXlBz7/BnC/A65KTHXkfYSPB6K1+u0VS2fnVM5hVcqzdudz5hwRTjgdiMIaRs7B7ZdCdbSm5+NGpcAy3QyzAD7m1RR5+HFkYVBF+Uc4NjMs20xWnENEDiWxUKOp1C7YI9mFdSoHfGIcHZ0Fh2SARqoD963nBOCwQY/Mejb1sd4C0QCj8xko4zSadvA/GWXExx1wEi6Hq6lMtd7Gxx3QQV/95AVXZaLhyx+MmJCkphFt7z8KAdNVnA24NLnOSLILHRKItHkUelqMfOf+D+tIziHgYLBR5nx0KVsK30fddXDeISMELl4VVOJQCtfcAi8yIsaR4EoTUWOzv2kt6gTJYDRhD5UTbv0I8+v/Ks6Lvhae20YAg7W4keNTCrgkrMxsVu7It79KSHXvFXaPvTUSbpyDEW+JHkJRvzfMAR47Cj0Zg+oXcec2bU7YwAtH8wpyJYAzb9o1x2LM8ZAFDHbI0VqNN2aAPUbxaVfAqqTVog4Ccxiy+8z8I63q35KI5maUiTnch8yW8MENV04+pXY2s4+/nboTCNdoxFScNMZ5kp6YpT228sQKGuyjw8s282c6sJbsHP5A4l7lCJqjpCHPLGaSS9RzSVskfoVVGuYpMA8tHcpFprKK9dCfCg8gA2qlnIKSXwGo7yq/s4MH2rHrvQLoHakcZzF38OMF3I6r1RcM/X8rAmRMZouPSWuDMbYwN/RhH3AyGHJSHcO9Ryq4VbMpLAETR4n7dTHGJhIZrOynDDB/EzTMw/80vAvq8nas
  template:
    metadata:
      name: bulletin-tunnel-credentials
      namespace: cloudflare
