---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    admin-password: AgCH8t/WEBwaY6ylDukMk2jz4GKTRi+ha0bTKlYsfz0i3b3mwIL97x/VtD/8FV1sZDKB7CYiwZx4Ky1EhkEoIwyASy4t3Si2KiSeaEjScW2YZmbtzpjoYQNp88Pwu4rw47byy6klfpFYc72PC3Cccdta4od8A08UTD0EW0gnHiXxmpuo90bFRa5iFKzD/xRxe6LioqFl/sZnBKKeY4h8e5OOqkaho3XKqnnI7Jma9/maEpWwZBXlm+pomeWOAIt/vRQC7yISflAhvL9Y9motGn1ORIvevSWX9w5+OyqcxEtFBu4hI7N7xHkHATdtRT92Kb5opO0EVOjvpI6mcS/n/ecOElXpKVQ1BWQAqmUsVrJVZV9Bj0V4BntbRnHCieEpr+qM2jEtqT94fnmCkX89ILIL7GiTLQhQDUlEEpYPXOYYGhJQgfHKe75aj+0Trx//7KyfW1ONzmAeTxCHgcuChsBMbD+g2B2XHOWbNHt5O8hHor7jxK/HrIAIlS4ly15N2q/mDtGiq+EobFUheXgrbATdOke4pWmG/qS3vLg67oh1JWQQVr2TibnfKPT73SsPKyGA6IOd01uVJA7nQWRRHMYtBiyoMvEwRheMKK5A7VvQygUc5d+GweO508dRSiv6ubewMk9q9SkSYiYIo3AbeMYyNUBvV7o9WHyZhmg3bnUW5iWzDyO2mxpH9rSW1N9Vblt6XJ5d3Vul5nISjiE1yOLRUiHrtYiMJCSRUbxfHuAIxg==
  template:
    metadata:
      name: nextcloud-secret
      namespace: nextcloud
