apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bulletin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jacoloves/argocd-apps.git
    targetRevision: master
    path: apps/bulletin
  destination:
    server: https://kubernetes.default.svc
    namespace: bulletin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
